language: "rust"
cache: "cargo"
before_script:
  - "rustup component add rustfmt"
  - "rustup component add clippy"
script:
  - "cargo fmt --all -- --check"
  - "cargo clippy --all-targets --all-features -- -D warnings"
  - "cargo build --all-features --verbose"
  - "cargo test --all-features --verbose"
