[package]
name = "js_int_ext_tests"
version = "0.1.0"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"
publish = false

[dependencies]
serde_json = "1.0"

[dependencies.js_int]
path = "../"
features = ["serde"]

[features]
lax_deserialize = ["serde_json/float_roundtrip"]
